controllers:
    resource: ../src/Controller/
    type: annotation
HomeController:
    path: /
    controller: App\Controller\HomeController::index
login:
    path: /login
    controller: App\Controller\AuthController::login
logout:
    path: /logout
    controller: App\Controller\AuthController::logout
post:
    path: /post
    controller: App\Controller\PostController::index
edit:
    path: /edit
    controller: App\Controller\PostController::edit
signup:
    path: /signup
    controller: App\Controller\AuthController::signup
contact:
    path: /contact/{id}
    controller: App\Controller\DetailsPageController::contacter
send_email:
    path: /send_email
    controller: App\Controller\DetailsPageController::sendEmail
admin:
    path: /admin
    controller: App\Controller\AdminController::index
kernel:
    resource: ../src/Kernel.php
    type: annotation
