controllers:
    resource: ../src/Controller/
    type: annotation
HomeController:
    path: /
    controller: App\Controller\HomeController::index
login:
    path: /login
    controller: App\Controller\AuthController::login
logout:
    path: /logout
    controller: App\Controller\AuthController::logout
kernel:
    resource: ../src/Kernel.php
    type: annotation
